services:
  s3:
    image: localstack/localstack:3.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./init-s3.py:/etc/localstack/init/ready.d/init-s3.py"

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379

  api:
    build: ./backend/deps
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/deps:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localhost:4566
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - s3
      - db
    restart: always

  celery:
    build: ./backend/deps
    command: celery -A debts worker -l INFO
    volumes:
      - ./backend/deps:/app
    environment:
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://s3:4566
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - s3
      - db
    restart: always
  
  db:
    image: postgres:alpine3.20
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./backend/deps:/app

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - "5555:5555"
    depends_on:
      - redis

  smtp:
    image: rnwood/smtp4dev:3.6.0-ci20240601108
    restart: always
    ports:
      - '5000:5000'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:5000

networks:
  default:
    driver: bridge

volumes:
  smtp4dev-data: